# Generated by Django 4.2.2 on 2023-07-06 01:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Artista_Model',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Obra_Model',
        ),
    ]
