# Generated by Django 4.2.2 on 2023-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_project_artista_model_rename_task_obra_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra_model',
            old_name='project',
            new_name='artista',
        ),
        migrations.RemoveField(
            model_name='artista_model',
            name='user',
        ),
        migrations.RemoveField(
            model_name='obra_model',
            name='user',
        ),
        migrations.AddField(
            model_name='artista_model',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista_model',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='artista_model',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artista_model',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
