# Generated by Django 4.2.2 on 2023-07-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_artista_model_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
