# Generated by Django 4.2.2 on 2023-07-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_obra_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_model',
            name='image',
            field=models.ImageField(upload_to='obras'),
        ),
    ]
