# Generated by Django 4.2.2 on 2023-07-06 03:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_obra_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_model',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='obras'),
        ),
    ]
